# file: nginx/tasks/sites.yml

- name: Nginx | Update the configurations for the sites inventory
  template:
    src: site.j2
    dest: "{{nginx_dir}}/conf.d/{{ svr.server_name }}.conf"

#- name: Nginx | Create virtual sites directories
#  file:
#    path: "{{nginx_www_dir}}/{{item.server.name}}"
#    state: directory
#    owner: "{{nginx_user}}"
#    group: "{{nginx_user}}"
#    mode: 0755
#  with_items: nginx_sites

