---
- hosts: localhost

  vars_files:
    - 'defaults/main.yml'

  roles:
    - { role: nginx, site: 'glast-ground.slac.stanford.edu', sitedir: "./sites"}
    - { role: nginx, site: 'srs.slac.stanford.edu', sitedir: "./sites"}
